### ISSUE TITLE
logs_fromで過去メッセージが取れない

### ISSUE THREAD

**Issue by kotmw0701** [kotmw0701/DGP_Auth_Python#2]
関数
```
def is_AuthOther(server, user):
    counts = 0
    msgiter = client.logs_from(server.get_channel(190495358843879428)).iterate()
    for message in msgiter:
        if msgiter is None:
            break
        if message in None:
            break
        if message.author.id != user.id:
            continue
        msg = message.content.replace('\r\n', '').replace('\r', '').replace('\n', '') .replace(' ', '').replace('　', '')
        counts += len(msg)
    return counts
```

エラー
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Kotmw0701\Documents\Development\Ecripce_WorkSpace\Discord_bot\Main.py", line 58, in on_message
    print(is_AuthOther(message.server, user))
  File "C:\Users\Kotmw0701\Documents\Development\Ecripce_WorkSpace\Discord_bot\Main.py", line 93, in is_AuthOther
    for message in msgiter:
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 1603, in _logs_from
    return self.http.logs_from(channel.id, limit, before=before, after=after, around=around)
AttributeError: 'NoneType' object has no attribute 'id'
```

[APIリファレンス](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.logs_from)見ても上手く動作しない・・・(´-ω-｀)

**Comment by kotmw0701** [comment]
for文と関数をasyncにして、itarate()を消す
ただこれだけを実行しても動作はしないから、実行するときに
await is_AuthOther(server, user)
と、前にawaitを付けないと動かない、
コルーチンオブジェクトとして呼び出されちゃう
```
async def is_AuthOther(server, user):
    counts = 0
    msgiter = client.logs_from(server.get_channel('190495358843879428'))
    async for message in msgiter:
```
